version: '2'
services:
 cobbler:
  build: .
  image: sigtom/cobbler:latest
  volumes:
   - /sys/fs/cgroup:/sys/fs/cgroup:ro
   - etc/cobbler/settings:/etc/cobbler
   - var/www/cobbler/images:/var/www/cobbler/images
   - var/www/cobbler/ks_mirror:/var/www/cobbler/ks_mirror
   - var/www/cobbler/links:/var/www/cobbler/links
   - var/lib/cobbler/config:/var/lib/cobbler/config
   - var/lib/tftpboot:/var/lib/tftpboot
   - dist/ubby:/mnt:ro
  ports:
   — “5432:5432”
   - "80:80"
   - "2202:22"
   - "69:69"
   - "25151:21515"
   - "873:873"
   - "443:443"
  network_mode: host











